stages:
- deploy
- sast
- test

deploy_dev:
  stage: deploy
  script:
    - export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v18.12.0/bin"
    - cd /home/ubuntu/backend_admin
    - pm2 delete backend_admin
    - git reset --hard
    - git pull
    - yarn install
    - yarn build
    - pm2 start "yarn start" --name="backend_admin"
    - pm2 save
  only:
    - develop
  tags:
    - c11_klaytn22184_backend_admin

deploy_uat:
  stage: deploy
  script:
    - export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v18.12.0/bin"
    - cd /home/ubuntu/backend_admin
    - pm2 delete backend_admin
    - git reset --hard
    - git pull
    - yarn install
    - yarn build
    - pm2 start "yarn start" --name="backend_admin"
    - pm2 save
  only:
    - staging
  tags:
    - c11_klaytn22184_backend_admin_uat

sonarqube-check:
  stage: sast
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint:
    - ''
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: '0'
  cache:
    key: "${CI_JOB_NAME}"
    paths:
    - ".sonar/cache"
  script:
  - sonar-scanner
  allow_failure: true
  only:
  - develop
  tags:
  - vmogroup
include:
- template: Security/Secret-Detection.gitlab-ci.yml
secret_detection:
  tags:
    - vmogroup
