version: '3.1'

services:
  klaytn_database:
    image: mongo:4.2.3-bionic
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_DATABASE=klaytn
      - MONGO_INITDB_ROOT_USERNAME=klaytn_root
      - MONGO_INITDB_ROOT_PASSWORD=klaytn_root_password
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - ./data:/data/db
  redis:
    image: redis:6-alpine
    command: redis-server --requirepass '${REDIS_PASSWORD}'
    ports:
      - 6379:6379